# Generated by Django 3.2.4 on 2021-07-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_date_published_question_pup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pup_date',
            field=models.DateTimeField(verbose_name='Date_published'),
        ),
    ]
